# install.packages("shiny")
# install.packages("tidyverse")
install.packages("here")
install.packages("GA")
install.packages("paletteer")
install.packages("ggsci")
install.packages("waiter")
install.packages("ggtext")
